<a href="https://colab.research.google.com/github/Ashwathguru/FML/blob/master/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pyplot as plt
import pandas as pd
dataset=pd.read_csv("Bank_Data.csv")
X=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values

In [4]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_1=LabelEncoder()
X[:,2]=labelencoder_X_1.fit_transform(X[:,2])
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [5]:
onehotencoder=OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray()
print(X)

X=X[:,1:]#dummy variable trap , leads to correlation of more than one variable


[[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [6]:
''' IF output has more than one variable
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)'''

' IF output has more than one variable\nlabelencoder_y=LabelEncoder()\ny=labelencoder_y.fit_transform(y)'

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()
#Adding input layer and the first hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11)) #uniform- initalizing weights that are close to zero
#adding the second hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu')) #relu rectified linear unit - it will converge the result
#overfitting in artifical nn how and why 

Instructions for updating:
Colocations handled automatically by placer.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':


In [12]:
#Adding Output Layer
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid')) #sigmoid - probablity of
#compiling ann
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy']) #adam-gradient descent approach / binary_crossentropy - classification
#fitting ann to training set
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100) #epoch- number of iterations

Instructions for updating:
Use tf.cast instead.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """


Epoch 1/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.4863 - acc: 0.7957
Epoch 2/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4261 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4176 - acc: 0.8165
Epoch 4/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4120 - acc: 0.8327
Epoch 5/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4076 - acc: 0.8320
Epoch 6/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4051 - acc: 0.8335
Epoch 7/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4036 - acc: 0.8340
Epoch 8/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4020 - acc: 0.8346
Epoch 9/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4008 - acc: 0.8351
Epoch 10/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4002 - acc: 0.8352
Epoch 1

In [0]:
#predict
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

In [15]:
#confusion martix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm


array([[1529,   66],
       [ 214,  191]])